[/Script/EngineSettings.GameMapsSettings]
; El nivel se genera por código, así que basta con el mapa vacío del motor.
GameDefaultMap=/Engine/Maps/Entry
EditorStartupMap=/Engine/Maps/Entry
GlobalDefaultGameMode=/Script/JJDoom.JJGameMode

[/Script/Engine.RendererSettings]
; Iluminación global y reflejos en tiempo real (Lumen) y sombras virtuales.
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Shadow.Virtual.Enable=1
r.GenerateMeshDistanceFields=True
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.AntiAliasingMethod=4

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
